services:
  db:
    image: postgres:13
    container_name: splitthat_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  cache:
    image: redis:8.2.1-alpine
    container_name: splitthat_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data

  backend:
    build: .
    container_name: splitthat_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  cache_data: